[tool.ruff]
line-length = 100
target-version = "py311"
exclude = ["db", "logs", ".venv", "venv", "frontend/dist", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]  # ignore long lines for now
