name: CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (exact commit)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pytest

      - name: Ruff lint
        run: ruff check .

      - name: Ruff format check (optional)
        run: ruff format --check .

      - name: Detect tests
        id: detect
        shell: bash
        run: |
          shopt -s globstar nullglob
          files=(tests/**/*_test.py tests/**/test_*.py)
          if (( ${#files[@]} )); then
            echo "found=true" >> "$GITHUB_OUTPUT"
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Pytest
        if: steps.detect.outputs.found == 'true'
        run: pytest -q

      - name: Skip pytest (no tests found)
        if: steps.detect.outputs.found != 'true'
        run: echo "No tests found under tests/. Skipping."
