name: CI

on:
  push:
    branches: [ main ]   # change "main" if your default branch is different
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff
      - name: Ruff (lint)
        run: ruff check .
      # Runs only if a tests/ folder exists
      - name: Pytest
        if: ${{ hashFiles('tests/**') != '' }}
        run: |
          pip install pytest
          pytest -q
